feat(megbrain): add pixel_shuffle opr
MegEngine/MegEngine pull request #211
Opened 2021-09-08 17:28 UTC by chenjiahui0131

2021-09-08 17:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=211) before we can accept your contribution.<br/><hr/>**chenjiahui** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=211) it.</sub>

2021-09-09 02:43 UTC, lixiangyin666 commented
这个op需要参与训练吗？没看到backward的实现

2021-09-09 02:46 UTC, lixiangyin666 commented
只实现了naive版本，确定不需要其他平台吗？如果只是为了训练，则还需要实现cuda，如果只是部署，则需要实现特定平台如ARM等

2021-09-09 06:02 UTC, chenjiahui0131 commented
> 只实现了naive版本，确定不需要其他平台吗？如果只是为了训练，则还需要实现cuda，如果只是部署，则需要实现特定平台如ARM等

本PR主要目的是实现naive pixelshuffle算子~

2021-09-09 10:23 UTC, lixiangyin666 requested changes

2021-09-09 10:23 UTC, lixiangyin666 commented on src/opr/impl/dnn/dnn.oprdecl
> +         params=[('param', 'Add')])
Add?

2021-09-09 10:23 UTC, lixiangyin666 commented on src/opr/include/megbrain/opr/search_policy/algo_chooser.h
> +#include "megbrain/opr/dnn/pixel_shuffle.h"
这里不需要添加头文件吧

2021-09-09 10:24 UTC, lixiangyin666 commented
> > 只实现了naive版本，确定不需要其他平台吗？如果只是为了训练，则还需要实现cuda，如果只是部署，则需要实现特定平台如ARM等
> 
> 本PR主要目的是实现naive pixelshuffle算子~

如果只是naive版本，为了训练也需要加上backward支持

2021-09-09 17:31 UTC, chenjiahui0131 commented on src/opr/include/megbrain/opr/search_policy/algo_chooser.h
> +#include "megbrain/opr/dnn/pixel_shuffle.h"
已删除

2021-09-09 17:31 UTC, chenjiahui0131 commented on src/opr/impl/dnn/dnn.oprdecl
> +         params=[('param', 'Add')])
已修复为PixelShuffle

2021-09-09 17:32 UTC, chenjiahui0131 commented on dnn/src/naive/pixel_shuffle/opr_impl.cpp
> +} //anonymous namespace
已删除

2021-09-09 17:32 UTC, chenjiahui0131 commented on dnn/src/common/pixel_shuffle.cpp
> +        megdnn_assert(input.ndim == 4);
修改为支持>=3维tensor

2021-09-09 17:33 UTC, chenjiahui0131 commented on imperative/python/megengine/functional/nn.py
> +    op = builtin.PixelShuffle(upscale_factor)
已补充文档，及参数判断

2021-09-10 02:51 UTC, lixiangyin666 requested changes

2021-09-10 02:51 UTC, lixiangyin666 commented on imperative/python/test/unit/functional/test_functional.py
> +    inp = np.arange(3 * 18 * 3 * 3).reshape(3, 18, 3, 3)
只测试了4维的？

2021-09-10 02:51 UTC, lixiangyin666 commented on imperative/python/megengine/functional/nn.py
> +    shape (*, C, H x r, W x r), where r is an upscale factor.
解释一下*是啥意思？

2021-09-10 02:51 UTC, lixiangyin666 commented on dnn/src/naive/pixel_shuffle/opr_impl.cpp
> +            std::memset(ptr_out, 0, sizeof(T) * output.layout.total_nr_elems());
这里需要memset为0吗？其他平台要和niave对齐，虽然naive不要求性能，但是memset操作会很慢

2021-09-10 06:42 UTC, chenjiahui0131 commented on imperative/python/test/unit/functional/test_functional.py
> +    inp = np.arange(3 * 18 * 3 * 3).reshape(3, 18, 3, 3)
> > > 只实现了naive版本，确定不需要其他平台吗？如果只是为了训练，则还需要实现cuda，如果只是部署，则需要实现特定平台如ARM等
> > 
> > 
> > 本PR主要目的是实现naive pixelshuffle算子~
> 
> 如果只是naive版本，为了训练也需要加上backward支持

已增加backward

2021-09-10 06:42 UTC, chenjiahui0131 commented on imperative/python/test/unit/functional/test_functional.py
> +    inp = np.arange(3 * 18 * 3 * 3).reshape(3, 18, 3, 3)
新增测试了3~7维

2021-09-10 06:42 UTC, chenjiahui0131 commented on imperative/python/megengine/functional/nn.py
> +    shape (*, C, H x r, W x r), where r is an upscale factor.
更新了对*的解释

2021-09-10 06:42 UTC, chenjiahui0131 commented on dnn/src/naive/pixel_shuffle/opr_impl.cpp
> +            std::memset(ptr_out, 0, sizeof(T) * output.layout.total_nr_elems());
删除了memset

2021-09-10 06:44 UTC, chenjiahui0131 commented
> > > 只实现了naive版本，确定不需要其他平台吗？如果只是为了训练，则还需要实现cuda，如果只是部署，则需要实现特定平台如ARM等
> > 
> > 
> > 本PR主要目的是实现naive pixelshuffle算子~
> 
> 如果只是naive版本，为了训练也需要加上backward支持

已增加backward支持

2021-09-10 08:25 UTC, lixiangyin666 requested changes

2021-09-10 08:25 UTC, lixiangyin666 commented on src/opr/impl/dnn/pixel_shuffle.cpp
> +}
可以用宏MEGDNN_OPR_INIT1来做，同时需要用宏MGB_IMPL_OPR_GRAD来声明如何求导，可以参考https://github.com/MegEngine/MegEngine/blob/master/src/opr/impl/dnn/images2neibs.cpp#L20-L32

2021-09-10 08:25 UTC, lixiangyin666 commented on src/opr/test/dnn/pixel_shuffle.cpp
> +    TEST(TestOprDNN, PixelShuffleForward)
只测试了forward，backward也需要测试

2021-09-10 08:25 UTC, lixiangyin666 commented on imperative/python/megengine/functional/nn.py
> +    assert upscale_factor > 0, "upscale_factor should larger than 0"
不仅functional实现，还需要实现module吧？

2021-09-10 08:28 UTC, lixiangyin666 commented
涉及到API change（添加API），请 reviewer审核

2021-09-10 15:36 UTC, chenjiahui0131 commented on src/opr/impl/dnn/pixel_shuffle.cpp
> +}
已使用MEGDNN_OPR_INIT1/3等宏，并增加求导声明

2021-09-10 15:37 UTC, chenjiahui0131 commented on src/opr/test/dnn/pixel_shuffle.cpp
> +    TEST(TestOprDNN, PixelShuffleForward)
已增加Backward相关测试

2021-09-10 15:37 UTC, chenjiahui0131 commented on imperative/python/megengine/functional/nn.py
> +    assert upscale_factor > 0, "upscale_factor should larger than 0"
已实现module

2021-09-13 06:36 UTC, lixiangyin666 requested changes

2021-09-13 06:36 UTC, lixiangyin666 commented on imperative/python/megengine/module/pixel_shuffle.py
> +    def __init__(self, upscale_factor: int):
可以参考其他module实现：

- 给__init__增加**kwargs参数，方便设置名字等kwargs
- 加上super().__init__(**kwargs)执行父类的__init__方法

2021-09-13 06:38 UTC, lixiangyin666 commented
@yzchen @gaohuazuo @wjfwzzc  @zhouyizhuang-megvii  这个PR有API change，请review API接口是否合理

2021-09-13 06:40 UTC, lixiangyin666 commented
others 
![lgtm](https://user-images.githubusercontent.com/62682607/133035608-61e3cb2d-8a9b-4891-8119-dc7fa3069f57.png)

2021-09-13 07:10 UTC, yzchen commented on dnn/src/common/pixel_shuffle.cpp
> +    void PixelShuffleBackward::deduce_layout(const TensorLayout &src,
这个函数仿佛没被用过

2021-09-13 07:14 UTC, yzchen commented on imperative/python/test/unit/functional/test_functional.py
> +def test_pixel_shuffle():
看起来当前 pixel_shuffle 没有 cuda 实现，所以 gpu pytest 基本上是过不去的。

2021-09-13 07:15 UTC, yzchen commented on imperative/python/test/unit/functional/test_functional.py
> +def test_pixel_shuffle():
如果目标就只是 naive，可以在 pytest 上标一些 mark，可以参考其他 pytest。

2021-09-13 07:15 UTC, chenjiahui0131 commented on imperative/python/megengine/module/pixel_shuffle.py
> +    def __init__(self, upscale_factor: int):
已修复

2021-09-13 07:17 UTC, xxr3376 commented
API 看起来没问题，但是我有疑问 PixelShuffle 是不是理论上是可以通过多次的 `reshape + dimshuffle` 得到呢？ 没特别仔细推过… @chenjiahui0131 

如果能通过多次 reshape + dimshuffle 得到的话，那么大概率会比直接 naive 模式速度快得多，目前的实现感觉就算写出来也很难实际用起来。

2021-09-13 07:18 UTC, xxr3376 requested changes

2021-09-13 07:30 UTC, lixiangyin666 commented on dnn/scripts/opr_param_defs.py
> +pdef('PixelShuffle').add_fields('int32', 'upscale_factor', '1')
这个改变不会引起兼容性问题，但是本地CI会挂

2021-09-13 07:42 UTC, xxr3376 commented on dnn/src/common/pixel_shuffle.cpp
> +    void PixelShuffleBackward::deduce_layout(const TensorLayout &src,
deduce_layout 是 MegDNN 的标准，用来告知内存分配器如何分配存储块

2021-09-14 13:15 UTC, chenjiahui0131 commented on dnn/src/common/pixel_shuffle.cpp
> +        TensorLayout output_expected;
已合并

2021-09-14 13:15 UTC, chenjiahui0131 commented on imperative/python/test/unit/functional/test_functional.py
> +def test_pixel_shuffle():
已增加mark

2021-09-14 13:16 UTC, chenjiahui0131 commented on dnn/scripts/opr_param_defs.py
> -          'NCHW44','NCHW44_DOT',
已修复

2021-09-14 13:21 UTC, chenjiahui0131 commented
> API 看起来没问题，但是我有疑问 PixelShuffle 是不是理论上是可以通过多次的 `reshape + dimshuffle` 得到呢？ 没特别仔细推过… @chenjiahui0131
> 
> 如果能通过多次 reshape + dimshuffle 得到的话，那么大概率会比直接 naive 模式速度快得多，目前的实现感觉就算写出来也很难实际用起来。

可以通过reshape+dimshuffle等效pixelshuffle的

2021-09-15 02:32 UTC, yzchen commented on dnn/scripts/opr_param_defs.py
> +pdef('PixelShuffle').add_fields('int32', 'upscale_factor', '1')
这个问题在这里反正也没办法解决，只能后面跑本地ci的时候才能修复了。

2021-09-15 06:38 UTC, xxr3376 commented
> 可以通过reshape+dimshuffle等效pixelshuffle的

@chenjiahui0131 有没有对比过 reshape + dimshuffle 模拟 pixelshuffle 的性能？在 input 比较大的时候，我怀疑比现在的 naive 算法要快不少…如果确实是这样的话，在不写 CUDA implement 的情况下，是不是在 C++ implement 的时候直接调用另外的几个算子或者用 subgraph 的功能反而比较好

2021-09-21 14:34 UTC, xxr3376 commented
@chenjiahui0131 赞！不过有两个小问题

1. 你没有调用 sync，你可能需要在计算前后都调用 `megengine.full_sync()` 来确保计算是做完了的，否则你只是测试了发射任务的时间，两者时间一致也就理所应当了
2. 我认为你需要测试不同 input size 下的性能，在 shape 比较大的时候也许可能容易看出两者的差别

P.S. 如果两者性能在各种 case 下都差不多，我觉得是不是可以在 python 层用 subgraph 先拼一下而不是直接在 C++ 层添加？

2021-09-21 15:23 UTC, chenjiahui0131 commented
```
def func1():
    inp = np.arange(100 * 100 * 100).reshape(100, 100, 100)
    inp = megengine.tensor(inp)
    out = F.pixel_shuffle(inp, upscale_factor=10)
    megengine.core._imperative_rt.core2.full_sync()
    return out


def func2():
    inp = np.arange(100 * 100 * 100).reshape(100, 100, 100)
    inp = megengine.tensor(inp)
    out = F.reshape(inp, (1, 10, 10, 100, 100))
    out = F.transpose(out, (0, 3, 1, 4, 2))
    out = F.reshape(out, (1, 1000, 1000))
    megengine.core._imperative_rt.core2.full_sync()
    return out


if __name__ == "__main__":
    res0 = func1().numpy()
    res1 = func2().numpy()
    assert((res0 == res1).all())
    print(f"pixel_shuffle: {timeit(func1, number=1000)}")
    print(f"reshape+dimshuffle+reshape: {timeit(func2, number=1000)}")
```

运行结果
```
pixel_shuffle: 38.41986481100321
reshape+dimshuffle+reshape: 7.9380161464214325
```

加上`full_sync`后，确实reshape+dimshuffle+reshape显著快了。
// 如果我full_sync没用错的话，好像没有`megengine.full_sync()`，然后grep了一把，看上去`megengine.core._imperative_rt.core2.full_sync()`最像

看上去action是去学习subgraph，然后在python上拼一个
@xxr3376

2021-09-22 05:36 UTC, chenjiahui0131 commented
已实现基于subgraph的pixelshuffle，并且性能测得和reshape+dimshuffle+reshape几乎一致。
PTAL @xxr3376

2021-09-22 05:59 UTC, xxr3376 commented
大赞！可以试试看 trace（包括 symbolic）模式下的结果是否正确，具体你可以参考这里 https://github.com/MegEngine/MegEngine/blob/master/imperative/python/test/unit/functional/test_functional.py#L149

2021-09-22 07:01 UTC, chenjiahui0131 commented
> 大赞！可以试试看 trace（包括 symbolic）模式下的结果是否正确，具体你可以参考这里 https://github.com/MegEngine/MegEngine/blob/master/imperative/python/test/unit/functional/test_functional.py#L149

已增加相关测试，PTAL
@xxr3376

2021-09-22 09:55 UTC, xxr3376 commented on imperative/python/test/unit/functional/test_functional.py
> +    def pixel_shuffle(data, r):
有了 `test_pixel_shuffle_symbolic` 这个函数的话，因为用 `None` 表达了非 trace 的情况，是不是这个测试是不必要的？

2021-09-22 10:22 UTC, chenjiahui0131 commented on imperative/python/test/unit/functional/test_functional.py
> +    def pixel_shuffle(data, r):
这个保留的目的是为了测dim=3~7进行对各维度tensor的完备测试。`test_pixel_shuffle_symbolic`拿其中一个例子，进行trace和symbolic的测试。兼具完备和效率~

2021-09-22 10:29 UTC, chenjiahui0131 commented on imperative/python/test/unit/functional/test_functional.py
> +    def pixel_shuffle(data, r):
我把`None`给移除了，来省这一次`冗余`的时间

2021-09-22 11:39 UTC, xxr3376 commented on imperative/python/test/unit/functional/test_functional.py
> +    def pixel_shuffle(data, r):
那是不是这个 pixel_shuffle 的 numpy 标准实现可以抽出来？避免写两次

2021-09-22 13:13 UTC, chenjiahui0131 commented on imperative/python/test/unit/functional/test_functional.py
> +    def pixel_shuffle(data, r):
fixed

2021-09-23 02:06 UTC, xxr3376 approved these changes

2021-09-23 03:12 UTC, lixiangyin666 commented on imperative/python/megengine/functional/nn.py
> +    outvar, *_ = apply(layerPixelShuffle(), inp, shape_0, shape_1)
这么做的话，这个op就不支持shape可变了吧？dump后shape不可变

2021-09-23 03:12 UTC, lixiangyin666 commented on imperative/python/megengine/functional/nn.py
> +        int(shape_ori[-3] / square),
这里不取int可以吗？如果shape_ori是tensor时会出错

2021-09-23 04:58 UTC, chenjiahui0131 commented on imperative/python/megengine/functional/nn.py
> +        int(shape_ori[-3] / square),
算子中assert已保证合法性，可以删除

2021-09-23 04:58 UTC, chenjiahui0131 commented on imperative/python/megengine/functional/nn.py
> +    outvar, *_ = apply(layerPixelShuffle(), inp, shape_0, shape_1)
shape已支持tensor

2021-09-23 05:01 UTC, lixiangyin666 approved these changes

2021-09-23 06:31 UTC, xxr3376 commented on imperative/python/megengine/functional/nn.py
> +    outvar, *_ = apply(layerPixelShuffle(), inp, shape_0, shape_1)
@lixiangyin666 感觉即便是不可变也没啥事，一般 PixelShuffle 都可以假设输入 shape 在推理时不变

2021-09-23 10:03 UTC, merged

2021-10-20 07:15 UTC, MegChai commented
@chenjiahui0131 看起来  Module 调用只能用 `megengine.module.pixel_shuffle.PixelShuffle` 的形式，我们预期用户能够通过 `M.PixelShuffle` 来调用，所以应该还需要加到 `module/__init__.py` .