docs(mge/functional): update functional.mul docstring
MegEngine/MegEngine pull request #398
Opened 2021-12-06 11:22 UTC by ErikQQY

2021-12-06 11:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=398) it.</sub>

2021-12-06 11:29 UTC, MegChai commented
👋 欢迎改进 MegEngine Python API Docstring.

`matmul` 这个 API 在 《数组 API 标准》中已经有了明确的定义：

https://data-apis.org/array-api/latest/API_specification/linear_algebra_functions.html#function-matmul

因此对于这个 API 我们还可以争取（或者说... 必须）做出更多的改进，具体改进建议会出现在 Code Review 环节。

2021-12-06 11:45 UTC, MegChai requested changes
整个流程中有不清楚的地方，欢迎艾特我提问～

2021-12-06 11:45 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
>  def mul(x, y):
函数签名这里没有添加（Type Hint）, 因此需要补上

2021-12-06 11:45 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +    r"""Returns the tensor representing the element-wise multiplication of the two input tensors(also known as Hadamard product).
为了和社区标准靠近，尽管这里的改动补充了很多细节 👍 👍 👍 
但我们是不是可以把这个信息放在 `Returns` 中去呢？Summary 太长的话还可能会影响 API 列表的展示效果。

Summary 部分在 《[数组 API 标准](https://data-apis.org/array-api/latest/API_specification/linear_algebra_functions.html#matmul-x1-x2)》中的定义是：

```
Computes the matrix product.
```

2021-12-06 11:45 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        x: input tensor.
这里的参数描述有些简单了，期望能够参考社区中的定义：

![image](https://user-images.githubusercontent.com/21091736/144839535-a6a15bc7-963e-4b38-8c85-b7626cbaf58f.png)

2021-12-06 11:45 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        output tensor.
和 Summary 部分有点关系，由于 Summary 部分写了太多细节，导致 `Returns` 这块就没东西写了。 

期望能够参考社区中的定义：

![image](https://user-images.githubusercontent.com/21091736/144839763-eff12881-4b61-4af8-8f51-6b6b5d993667.png)

2021-12-06 11:45 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        .. testcode::
MegEngine 的 Docstring 正在逐步地废弃掉 `testcode` 这种做法，可以参考

https://github.com/MegEngine/MegEngine/pull/386/files 这里的改动使用 `>>>` 样式。

2021-12-06 12:10 UTC, MegChai requested changes
参考《数组 API 标准》中的 `mul` 定义做了一些改动。

2021-12-06 12:10 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +    r"""Returns the tensor representing the element-wise multiplication of the two input tensors(also known as Hadamard product).
```suggestion
    r"""Calculates the product for each element :math:`x_i` of the input tensor `x` with the respective element :math:`y_i` of the input tensor `y`.
```

2021-12-06 12:10 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        x: input tensor.
```suggestion
        x: first input tensor. Should have a numeric data type.
```

2021-12-06 12:10 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        y: input tensor.
```suggestion
        y: second input tensor. Must be compatible with `x` (see :ref:`broadcasting-rule` ). Should have a numeric data type.
```

这里的 :ref:`broadcasting-rule` 在生成文档时会指向：

https://megengine.org.cn/doc/stable/zh/user-guide/model-development/functional/manipulation.html#broadcasting-rule

2021-12-06 12:10 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        output tensor.
```suggestion
        an tensor containing the element-wise products. The returned array must have a data type determined by :ref:`dtype-promotion`.
```

这里的 :ref:`dtype-promotion` 在生成文档时会指向：

https://megengine.org.cn/doc/stable/zh/user-guide/model-development/tensor/dtype.html#dtype-promotion

2021-12-06 12:59 UTC, ErikQQY commented
已修改，麻烦重新review

2021-12-06 13:27 UTC, MegChai requested changes
目前的预览效果如下所示：

![image](https://user-images.githubusercontent.com/21091736/144854078-bfa3170e-db51-45f7-9e7f-d3ea9d803303.png)

整体已经比原来那个孤零零的 `mul` 页面好很多了，👍👍👍👍 

希望能够在 Example 方面争取再改进一下～

2021-12-06 13:27 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +def mul(x, y) -> Tensor:
```suggestion
def mul(x: Tensor, y: Tensor) -> Tensor:
```

参数的类型提示也需要添加哦～

2021-12-06 13:27 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        * If either :math:`x_i` or :math:`y_i` is NaN , the result is `NaN`.
```suggestion
        * If either :math:`x_i` or :math:`y_i` is `NaN`, the result is `NaN`.
```

2021-12-06 13:27 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        * If :math:`x_i` and :math:`y_i` have different mathematical signs, the result has a negative mathematical sign, unless the result is `NaN`.
可以适当换行，限制改进一下 Docstring 中段落的长度，不要完全放在一行，方便阅读源码：

```rst
    Note:
        * If either :math:`x_i` or :math:`y_i` is `NaN`, the result is `NaN`.
        * If :math:`x_i` is either `+infinity` or `-infinity` and :math:`y_i` is either `+0` or `-0`, the result is `NaN`.
        * If :math:`x_i` is either `+0` or `-0` and :math:`y_i` is either `+infinity` or `-infinity`, the result is `NaN`.
        * If :math:`x_i` and :math:`y_i` have different mathematical signs, the result has a negative mathematical sign, unless the result is `NaN`.
        * If :math:`x_i` is either `+infinity` or `-infinity` and :math:`y_i` is either `+infinity` or `-infinity`,
          the result is a signed infinity with the mathematical sign determined by the rule already stated above.
        * If :math:`x_i` is either `+infinity` or `-infinity` and :math:`y_i` is a nonzero finite number, 
          the result is a signed infinity with the mathematical sign determined by the rule already stated above.
        * If :math:`x_i` is a nonzero finite number and :math:`y_i` is either `+infinity` or `-infinity`, 
          the result is a signed infinity with the mathematical sign determined by the rule already stated above.
        * In the remaining cases, where neither `infinity` nor `NaN` is involved,
          the product must be computed and rounded to the nearest representable value according to IEEE 754-2019 and a supported rounding mode.
          If the magnitude is too large to represent, the result is an `infinity` of appropriate mathematical sign.
          If the magnitude is too small to represent, the result is a zero of appropriate mathematical sign.
```

2021-12-06 13:27 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +
原 Specification 中有如下 Note:

```rst
    Note:
        Floating-point multiplication is not always associative due to finite precision.
```

这个提示也是有必要的，否则一些使用者可能会忽视掉这种情况。

2021-12-06 13:27 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +    Examples:
MegEngine 中的一些 API Example 其实槽点满满，比如这里用的例子其实不是很直观。

一种方法是看看 NumPy 的做法：

https://numpy.org/doc/stable/reference/generated/numpy.multiply.html

你也可以想想，提供哪些例子，能够快速地让读者照猫画虎地学会如何使用。

如果一个 API Example 不够直观，甚至需要用户花时间去验证正确性，体验会很差的。

2021-12-06 13:54 UTC, ErikQQY commented on imperative/python/megengine/functional/elemwise.py
> +    Examples:
我将例子换成了2x3矩阵与一维向量的积，比原来两个矩阵的例子更直观一些

2021-12-06 14:09 UTC, MegChai requested changes
除了例子的完备程度还不大够以外，Others, LGTM.

2021-12-06 14:09 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +    Examples:
赞，看来你这个 PR 还差最后一点可做的改进了。关于 Example, 我有一些主观的看法：

- 除非是为了展示区别，否则使用 `dtype` 参数的默认值，不然加这个参数没有多大借鉴意义；
- 对于 `mul` 这种等价于 `*` 操作符的 API，在 Example 中应该提供相应用法的例子（如 NumPy 所做的）。

因此我建议像这样去丰富你的用例：

```
    Examples:
        >>> F.mul(2, 3)
        Tensor(6, dtype=int32, device=xpux:0)

        >>> F.mul(2.0, 3.0)
        Tensor(6.0, device=xpux:0)

        >>> x = F.arange(6.0).reshape((2, 3))
        >>> y = F.arange(3.0)
        >>> F.mul(x,y)
        Tensor([[ 0.  1.  4.]
         [ 0.  4. 10.]], device=xpux:0)

        The `*` operator can be used as a shorthand for :func:`~functional.mul` on tensors.

        >>> x = F.arange(6.0).reshape((2, 3))
        >>> y = F.arange(3.0)
        >>> x * y
        Tensor([[ 0.  1.  4.]
         [ 0.  4. 10.]], device=xpux:0)
```

2021-12-06 14:11 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +    Examples:
在能够避免使用 NumPy 接口的情况下，尽可能用 MegEngine 的已有接口，比如使用 `F.arange` 代替 `np.arange`. 我们无法确保用户是有 NumPy 使用经验的。

2021-12-06 14:20 UTC, ErikQQY commented
已重新添加～

2021-12-06 14:24 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        The `*` operator can be used as a shorthand for :func:`~functional.mul` on tensors.
```suggestion
        The `*` operator can be used as a shorthand for :func:`~.functional.mul` on tensors.
```

我打的时候疏忽了，这里需要加个 `.` 不然找不到对应 API, 原因见：

https://megengine.org.cn/doc/stable/zh/development/docs/restructuredtext.html#python

2021-12-06 14:30 UTC, ErikQQY commented on imperative/python/megengine/functional/elemwise.py
> +        The `*` operator can be used as a shorthand for :func:`~functional.mul` on tensors.
已修复，麻烦啦

2021-12-06 14:34 UTC, MegChai approved these changes
Others, LGTM. 整体预览效果如下：

![b6a69b6e-3205-46af-b74a-5e36c000de96](https://user-images.githubusercontent.com/21091736/144865463-154f3a7c-7c58-468a-885f-649d19a118fd.png)

CI 跑通后，其他人也 Approve 的话就可以合入了。

P.S: 如果有时间的话，还可以提供 Docstring 对应的中文翻译，在下个版本的文档翻译流程中可以直接用到。

2021-12-07 01:39 UTC, ErikQQY commented
CI 貌似挂掉了😢

2021-12-07 03:08 UTC, MegChai commented
> CI 貌似挂掉了😢

看 log 应该不是你这个 PR 的问题，我给相关人员反馈一下。

2021-12-08 12:29 UTC, MegChai commented
@ErikQQY CI 跑通了，🎉 你还需要用 `git rebase` 将你的多个 commi 合并成一个，才能满足合并要求。

2021-12-08 13:38 UTC, ErikQQY commented
@MegChai 已rebase，麻烦review下～

2021-12-08 13:45 UTC, MegChai approved these changes
Others, LGTM

2021-12-13 09:26 UTC, daisycx approved these changes
LGTM

2021-12-17 06:26 UTC, merged