docs(mge/functional): updata functional.ones docstring
MegEngine/MegEngine pull request #399
Opened 2021-12-06 12:48 UTC by Asthestarsfalll

Fix: #232 
1.  按照 《Python 文档字符串风格指南》中的说明，发现 ones 在《数组 API 标准》中存在 标准定义，使用了《标准》中的文档字符串作为描述内容。
2. 修改了简述使其更清晰准确
2. 为`shape`, `dtype`和`device`添加了类型提示。
3. 使用`>>>`标准doctest风格替换掉原本的`testcode`风格样例

**翻译对比如下**：
Summary:
* Returns a tensor with given shape filled with value one
* 返回一个具有给定形状的全1张量

Args:
* shape (`list`, `tuple`, `integer`): the shape of the output tensor.
* shape (`list`, `tuple`, `integer`): 输出张量的形状.
* dtype (`str`) : the desired data type of the output tensor. Default: ``float32``.
* dtype (`str`) :输出张量的数据类型。默认值：``float32``.
* device (`Tensor.device`): the desired device of the output tensor. Default: if ``None``, use the default device (see: func:`~.megengine.get_default_device`).
* device (`Tensor.device`): 输出张量的设备。默认：如果为`None`，则使用默认设备（见函数`megengine.get_default_device`）

Returns:
* output tensor.
* 输出张量

2021-12-06 12:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=399) it.</sub>

2021-12-06 13:50 UTC, MegChai requested changes
需要做一些修改。

2021-12-06 13:50 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        shape (list, tuple, integer): the shape of the output tensor.
我建议 `shape` 参数的 type hint 用 numpy 的表述进行覆盖，

```suggestion
        shape (int or sequence of ints): the shape of the output tensor.
```

不同类型的 `shape` 输入可以在 Example 中体现。

2021-12-06 13:50 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +    r"""Returns a tensor with given shape filled with value one.
为什么这里不用《标准》中的原文呀？

```suggestion
    r"""Returns a new tensor having a specified shape and filled with ones.
```

2021-12-06 13:50 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        dtype (str) : the desired data type of the output tensor. Default: ``float32``.
```suggestion
        dtype (:attr:`.Tensor.dtype`, optional) : output tensor data type. If `dtype` is `None`, the output tensor data type must be the default floating-point data type. Default: `None`.
```

2021-12-06 13:50 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        device (Tensor.device): the desired device of the output tensor. Default: if ``None``,
```suggestion
        device (:attr:`.Tensor.device`, optional): device on which to place the created tensor. Default: `None`.
```

2021-12-06 13:50 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
>      Examples:
这里建议参考 NumPy 中给出的 Example:

https://numpy.org/doc/stable/reference/generated/numpy.ones.html

尤其是在不设置 `dtype` 时，`ones(5)` 默认会得到 `float32` 类型的 tensor.

2021-12-06 13:50 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        dtype (str) : the desired data type of the output tensor. Default: ``float32``.
这里其实有待讨论，从向标准一致的角度，应该原封不动地保留它们提供的 Docstring, 但是实际上这里的 `the default floating-point data type` 在 MegEngine 中就是 `float32` 想听听你的看法。

2021-12-06 13:51 UTC, MegChai commented
@Asthestarsfalll 需要签署一下 CLA. 在 2 楼可以看到。

2021-12-06 14:13 UTC, Asthestarsfalll commented on imperative/python/megengine/functional/tensor.py
> +        dtype (str) : the desired data type of the output tensor. Default: ``float32``.
我更偏向于修改Default为`float32`，一是用户查看时更加简单方便，二是`functional.ones`定义时`dtype`默认值为`float32`。

2021-12-06 14:16 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        dtype (str) : the desired data type of the output tensor. Default: ``float32``.
嗯嗯，碰到这种情况，还是尽可能保证用户体验吧，这里就不和《标准》严格对齐了。

2021-12-06 14:40 UTC, Asthestarsfalll commented
已修改并添加样例

2021-12-06 14:56 UTC, MegChai commented
这里的 `dtype` 和 `device` 严格来说是关键字参数，因此在 Docstring 中要对不同类型的参数进行显式的区分：

```
    Args:
        shape (int or sequence of ints): the shape of the output tensor.

    Keyword args:
        dtype (:attr:`.Tensor.dtype`): output tensor data type. Default: ``float32``.
        device (:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
```

2021-12-06 15:05 UTC, MegChai commented
与此同时，还希望帮忙在函数签名中加入分隔符 `*`:

```python
def ones(
    shape: Union[int, Tuple[int, ...]],
    *,
    dtype="float32", 
    device: Optional[CompNode] = None
) -> Tensor:
```

2021-12-06 15:25 UTC, MegChai commented
CI / check-commit 挂了，注意 commit message 的格式，理想中应当是这样的：

```shell
git commit -m "docs(mge/functional): updata functional.ones docstring"
```

对于你这个 PR, 需要 `git rebase -i dev` 然后修改第一个 commit 的 message，其它的 commit 可以以 fixup 的形式合并进来，然后将整个单独的 commit 强制 push 上来。

2021-12-07 12:41 UTC, MegChai approved these changes
Others, LGTM.

2021-12-07 12:42 UTC, momoComeOn commented
谢谢您的邮件，我会尽快回复！

2021-12-08 03:25 UTC, MegChai commented
看来需要在这个 PR 中协助修复单元测试 test_one_hot 中不规范的写法，否则你也选择等官方修完同步过来（时间可能会久一些）

2021-12-08 04:36 UTC, Asthestarsfalll commented
已修复`nn.py`中`one_hot`中的不规范写法

2021-12-09 08:37 UTC, MegChai approved these changes
Others, LGTM.

2021-12-17 11:14 UTC, merged