docs(mge/functional)
MegEngine/MegEngine pull request #401
Opened 2021-12-07 03:50 UTC by LosReturn

updata functional.clip docstring

2021-12-07 03:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=401) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=401) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=401) it.</sub>

2021-12-07 03:53 UTC, MegChai commented
感谢贡献 🎉 为了使得该 PR 能被合入，你还需要签署 CLA 协议，修改 commit message 格式。

必须要在 #266 留下评论，才能 Assign 作为 Issue 的负责人

2021-12-07 04:58 UTC, MegChai requested changes
需要做一些改进，可以多玩一玩 clip 这个接口，看这里的描述是否覆盖到了所有能够想到的情况

2021-12-07 04:58 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
>      Examples:
给出的例子不太合适，我们在上面的类型提示中暗示了应当传入 Tensor 类型的 `input` 参数，而在例子中实际上传进去的是一个 List, 尽管底下做了转换，但你的参数解释和你的例子的前后描述就不一致了，

2021-12-07 04:58 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        lower (int): lower-bound of the range to be clamped to.
能够接受的类型不只是 `int`

2021-12-07 05:03 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
>      Examples:
以及需要对特殊情况 `min` > `max` 的时候会发生什么，进行说明

2021-12-07 05:07 UTC, LosReturn commented on imperative/python/megengine/functional/elemwise.py
>      Examples:
好的，我修改下

2021-12-07 05:32 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
>      Examples:
嗯嗯，我建议你用 git 命令行或者 gui 工具来操作，GitHub web 编辑器虽然简单方便，但是不利于做后续的改动

2021-12-08 08:36 UTC, LosReturn commented
sorry，终于有点理解这个--amend 怎么用了。

2021-12-08 08:39 UTC, LosReturn commented
@MegChai 麻烦您review下

2021-12-08 13:51 UTC, MegChai commented
你的 commit 历史有点乱，需要用 `git rebase` 整理合并成一个单独的 commit

2021-12-09 03:37 UTC, LosReturn commented
okay，I address

2021-12-09 08:41 UTC, MegChai requested changes

2021-12-09 08:41 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        *If both `lower` and `upper` are None, raises an AssertionError.
样式不对哦， `*` 必须和英文单词之间有一个空格，不然渲染出来的样式会变成普通段落

2021-12-09 08:41 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        lower (Numberic，optional): lower-bound of the range to be clamped to.
这里为什么选择使用 `Numberic` 而不是 `Number or Tensor` 之类的描述呢？

2021-12-09 08:41 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        >>> x = megenine.Tensor([0,1,2,3,4])
这几个例子都很好，还可以做的改进是：

* megengine.Tensor -> Tensor
* megenine.functional -> F

可替换的规则在这里：https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/conftest.py

2021-12-09 09:58 UTC, LosReturn commented on imperative/python/megengine/functional/elemwise.py
> +        lower (Numberic，optional): lower-bound of the range to be clamped to.
Numberic 一般代表整数，浮点；Number 的话我认为范围更广一些，有涉及复数。

2021-12-10 04:35 UTC, MegChai commented on imperative/python/megengine/functional/elemwise.py
> +        lower (Numberic，optional): lower-bound of the range to be clamped to.
了解了，但是现在还没有复数类型的支持，为了以后出现相关的矛盾，我根据你这个情况在 Docstring 指南里面补充了一下统一的语义参考：https://megengine.org.cn/doc/stable/zh/development/docs/python-docstring-style-guide.html#docstring-typehint

单目前这个 PR ，它的修改已经是合格的了，我个人能接受。（不过如果你不嫌麻烦的话，可以再改成一致的 Number 描述，比心）

2021-12-10 04:36 UTC, MegChai approved these changes
Other, LGTM. 一些细节上还有提升空间，但不影响本 PR 合入质量。

2022-01-19 09:05 UTC, merged