docs(mge/functional): update functional.tensor.reshape docstring
MegEngine/MegEngine pull request #402
Opened 2021-12-07 05:43 UTC by AA1HSHH

根据 #237  中的描述改进 megengine.functional.reshape API 文档，改进方式如下：

按照 《Python 文档字符串风格指南》中的说明，发现 reshape 在《数组 API 标准》中存在 标准定义，因此使用了《标准》中的文档字符串作为描述内容。
# 翻译对比如下
---

   Summary:

- r"""Reshapes a tensor without changing its data.

-  不改变数据的情况下对张量变形。

Args:

-  inp: input tensor to reshape.

-  inp:输入需要变形的张量。

-  target_shape: target shape compatible with the original shape. One shape dimension is allowed 
             to be -1 . When a shape dimension is -1 , the corresponding output tensor shape dimension 
             must be inferred from the length of the tensor and the remaining dimensions.

-   target_shape:目标形状需要与源形状兼容。一个目标形状的维度可以是-1。当目标形状的维度是-1时，最终输出其对应的张量的形状维度会从张量的长度和剩余维度中推算出来。

Returns:

-   an output tensor having the same data type, elements, and underlying element order as inp .

-   输出的张量与输入的张量具有相同的数据类型、元素和元素排列顺序。

2021-12-07 05:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=402) it.</sub>

2021-12-07 05:49 UTC, MegChai commented
需要去 #237 简单回复一下，方便进行 Assign

2021-12-07 07:23 UTC, MegChai requested changes

2021-12-07 13:00 UTC, AA1HSHH commented
@MegChai 已经修改，麻烦再帮我看看。

2021-12-08 03:30 UTC, MegChai requested changes

2021-12-08 03:30 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
>              from megengine import tensor
Example 这里有一些 import 操作可以省略，可以参考这个文件：

https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/conftest.py

省略一些 import 操作可以让 Example 看起来更简洁清晰

2021-12-08 03:30 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +            >>> x = tensor(np.arange(12, dtype=np.int32))
- 使用 F.arange 代替 np.arange
- 不带 dtype 用也行，如无必要的话 example 中请使用默认参数

2021-12-08 03:30 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +            >>> print(x)
不需要使用 print，可以直接 x

2021-12-08 03:30 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +            >>> out = F.reshape(x, (3, 4))
这里可以直接 `F.reshape(x, (3, 4))` 不需要 out 也不需要 print 也不需要 .numpy

2021-12-08 03:30 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +            >>> out = F.reshape(x, (3, 4))
原来的代码中的 testcode 和 testouput 是不规范写法，造成了误导

2021-12-08 12:46 UTC, AA1HSHH commented on imperative/python/megengine/functional/tensor.py
> +            >>> out = F.reshape(x, (3, 4))
@MegChai 又改了一版，能帮我看看吗，谢谢！

2021-12-08 12:46 UTC, AA1HSHH commented
@MegChai 又改了一版，能帮我看看吗。谢谢！

2021-12-08 12:53 UTC, MegChai requested changes
除了 Example 格式可能导致 CI 挂了外，其它地方没什么要求了。

2021-12-08 12:53 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +            >>> F.reshape(x, (3, 4))
先让 CI 跑起来了，感觉你的 pytest 会挂在输出格式上

```shell
>>>F.reshape(x, (3, 4))
Tensor([[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], device=xpux:0)
```

`[` 默认没有对齐的，和 NumPy 不一样。

2021-12-08 13:27 UTC, AA1HSHH commented on imperative/python/megengine/functional/tensor.py
> +            >>> F.reshape(x, (3, 4))
OK,我改下再推上来。

2021-12-08 13:48 UTC, MegChai approved these changes
Others, LGTM

2021-12-09 04:39 UTC, AA1HSHH commented
@MegChai 果然CI挂了，怎么办:cry:

2021-12-10 04:32 UTC, MegChai commented
> @MegChai 果然CI挂了，怎么办😢

外面的 CI 资源比较紧张，所以有的时候会出现概率性挂，和 PR 修改本身无关，这个时候重跑一下 CI, 耐心等等就行啦～

2021-12-10 08:42 UTC, AA1HSHH commented
@MegChai CI还是挂了，话说是不是权限问题，我自己是没法重跑CI的，没有找到github文档说的Re-run jobs drop-down menu。

2021-12-11 13:11 UTC, MegChai commented
> @MegChai CI还是挂了，话说是不是权限问题，我自己是没法重跑CI的，没有找到github文档说的Re-run jobs drop-down menu。

昨天 GitHub Actions 官方服务出了问题，因此所有 CI 都受到了一些影响。让我们再跑一次 CI.

2021-12-13 02:28 UTC, AA1HSHH commented
@MegChai 为啥我的CI总是过不去啊 😥，怎么感觉这个错误我改不了的。
```
=================================== FAILURES ===================================
____________________________ test_persistent_cache _____________________________

    def test_persistent_cache():
        pc = PersistentCacheOnServer()
        k0 = b"\x00\x00"
        k1 = b"\x00\x01"
        cat = "test"
        pc.put(cat, k0, k1)
        pc.put(cat, k1, k0)
>       assert k1 == pc.get(cat, k0)
E       AssertionError: assert b'\x00\x01' == None
E         -b'\x00\x01'
E         +None

test/unit/utils/test_utils.py:14: AssertionError
=============================== warnings summary ===============================
/usr/local/lib/python3.6/dist-packages/_pytest/mark/structures.py:322
  /usr/local/lib/python3.6/dist-packages/_pytest/mark/structures.py:322: PytestUnknownMarkWarning: Unknown pytest.mark.require_ngpu - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

/usr/local/lib/python3.6/dist-packages/_pytest/mark/structures.py:322
  /usr/local/lib/python3.6/dist-packages/_pytest/mark/structures.py:322: PytestUnknownMarkWarning: Unknown pytest.mark.isolated_distributed - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

/usr/local/lib/python3.6/dist-packages/_pytest/mark/structures.py:322
  /usr/local/lib/python3.6/dist-packages/_pytest/mark/structures.py:322: PytestUnknownMarkWarning: Unknown pytest.mark.require_higher_order_directive - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
= 1 failed, 875 passed, 41 skipped, 189 deselected, 3 warnings in 174.17s (0:02:54) =
BDB0060 PANIC: fatal region error detected; run recovery
Error: Process completed with exit code 1.
```

2021-12-13 04:50 UTC, AA1HSHH commented
@MegChai CI还是没过，报错和之前的相同。麻烦帮我看看，谢谢！

2021-12-13 11:38 UTC, MegChai commented
老是挂在你这个 PR 上也太过于灵异了... 我选择再造一个 #412 试试看。

放心，如果不是你的 PR 引入的 CI 问题，会有很多解决思路的，不要被这个事情困扰到 = = Sry.

2021-12-17 00:58 UTC, AA1HSHH commented
@MegChai 看 #412 CI就过了的，真奇怪啊:confused:

2022-01-14 08:40 UTC, GetUpEarlier approved these changes
LGTM

2022-01-19 09:05 UTC, merged