docs(mge/functional): update functional.eye docstring
MegEngine/MegEngine pull request #404
Opened 2021-12-08 11:05 UTC by Olalaye

2021-12-08 11:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=404) before we can accept your contribution.<br/><hr/>**tanglin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=404) it.</sub>

2021-12-08 11:53 UTC, MegChai requested changes

2021-12-08 11:53 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
>      Args:
还需要补充一下 `dtype` 和 `device` 两个参数

2021-12-08 11:53 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +                [0. 1. 0.]
这里得到的输出的 `[` 符号不会和 NumPy 一样对齐，会导致 CI 过不了测试而挂掉。应当使用实际得到的输出。

2021-12-08 13:06 UTC, Olalaye commented on imperative/python/megengine/functional/tensor.py
> +                [0. 1. 0.]
不好意思，不太理解这里的问题是什么？这个输出是直接从MegStudio复制的，只是为了好看做了缩进。

2021-12-08 13:15 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +                [0. 1. 0.]
这里的 Example 是会跑 CI 测试 Pytest 的，输出的内容是严格比对的，如果为了好看做缩进会等同于在测试的时候得到一个非预期的输出，导致 CI 挂掉。

2021-12-08 13:16 UTC, MegChai commented
请签署 CLA 安全协议，链接在 2楼

2021-12-09 06:11 UTC, Olalaye commented on imperative/python/megengine/functional/tensor.py
>      Args:
已经补充了dtype 和 device参数为 Keyword args

2021-12-09 06:12 UTC, Olalaye commented on imperative/python/megengine/functional/tensor.py
> +                [0. 1. 0.]
已经取消手动缩进

2021-12-09 08:36 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +                [0. 1. 0.]
是的，起始位置与 >>> 的开头对齐

2021-12-10 04:28 UTC, MegChai requested changes
只剩两个细节的地方需要修改，我这边就能 Approve 了。

2021-12-10 04:28 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        dtype( :attr:`.Tensor.dtype` ): output tensor data type. Default: ``float32``.
这里其实是一开始的 arange PR 中没有注意细节，空格的位置不对，应当是

```
dtype (:attr:`.Tensor.dtype`)
``` 

这种写法. 下面的 `device` 参数同理。

2021-12-10 04:28 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        >>> F.eye(N=3)
对于位置参数，统一看作是仅位置参数（将来可能会变成强制要求），使用时不要带上参数名；

参考这里的解释：

https://megengine.org.cn/doc/stable/zh/development/docs/python-docstring-style-guide.html#docstring-example

2021-12-10 05:56 UTC, Olalaye commented on imperative/python/megengine/functional/tensor.py
> +        >>> F.eye(N=3)
已修改

2021-12-10 08:41 UTC, MegChai approved these changes
除了还有两个空格的细节问题外， Others, LGTM.

2021-12-10 08:41 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        dtype(:attr:`.Tensor.dtype`): output tensor data type. Default: ``float32``.
```suggestion
        dtype (:attr:`.Tensor.dtype`): output tensor data type. Default: ``float32``.
```

2021-12-10 08:41 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        device(:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
```suggestion
        device (:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
```

2021-12-13 11:42 UTC, MegChai commented
你的 commit 历史需要使用 `git rebase` 整理成单个的，然后 `git push --force`` 推送上来

2021-12-16 01:44 UTC, Olalaye commented
> 你的 commit 历史需要使用 `git rebase` 整理成单个的，然后 `git push --force`` 推送上来

已经rebase

2021-12-16 08:13 UTC, MegChai approved these changes
Others, LGTM.

2021-12-17 01:35 UTC, Olalaye commented
@MegChai CI挂了，麻烦帮忙看看是什么问题

2022-01-21 02:54 UTC, HuaHua404 commented
> @MegChai CI挂了，麻烦帮忙看看是什么问题

@Olalaye  可以查看下最新的回复 “MegEngine CI修复通知 #420”。需要您 rebase 最新的 master 分支。如果对 rebase 操作有任何疑问，可加入 MegEngine 技术交流 QQ 群讨论，QQ 群号：1029741705

2022-09-28 11:01 UTC, kagome1007 commented
因长期未有后续操作，已交由其他同学处理。感谢对 MegEngine 的支持，期待后续你的贡献哦！

2022-09-28 11:01 UTC, closed without merging