docs(mge/functional): update functional.full docstring
MegEngine/MegEngine pull request #409
Opened 2021-12-10 07:16 UTC by Olalaye

关联issue：https://github.com/MegEngine/MegEngine/issues/234

该 API 为 MegEngine Tensor 生成操作相关的 API, 对应文档页面在 [megengine.functional.full](https://megengine.org.cn/doc/stable/zh/reference/api/megengine.functional.full.html)

参考 [《Python 文档字符串风格指南》](https://megengine.org.cn/doc/stable/zh/development/docs/python-docstring-style-guide.html)做了以下修改：

- 为了与其他API描述一致，对文字描述做了少量修改。
- 替换掉了 testcode 风格的样例，使用 >>> 标准 doctest 风格。

## 翻译对比如下：
Summary:

- Return a tensor of shape ``shape`` filled with ``value``.
返回一个形状为``shape``，值为``value``的张量

Args:

- shape: output tensor shape.
shape: 输出张量的形状。
- value: fill value.
value: 输出张量的填充值。

Keyword args:

- dtype(:attr:`.Tensor.dtype`): output tensor data type. If ``dtype`` is ``None``, the output tensor data type must be inferred from ``value``. If the value is an ``int``, the output tensor data type must be the default integer data type. If the value is a ``float``, the output tensor data type must be the default floating-point data type. If the value is a ``bool``, the output tensor must be a boolean data type. Default: ``None``.
 dtype(:attr:`.Tensor.dtype`): 输出张量的类型。如果``dtype``的值为 ``None``，输出张量数据类型会从``value``推断出来。如果值是一个``int``，输出张量数据类型必须是默认的整数数据类型。如果值是一个``float``，输出张量数据类型必须是默认的浮点数据类型。如果值是一个``bool``，输出张量必须是布尔数据类型。默认值：``None``。

- device(:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
device(:attr:`.Tensor.device`): 用来放置所创建张量的设备。 默认值： ``None``。

Returns:
- A tensor where every element is equal to ``value``.
一个每个元素都等于``value``的张量。

2021-12-10 08:38 UTC, MegChai requested changes

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +    r"""Return a tensor of shape ``shape`` filled with ``value``.
```suggestion
    r"""Returns a new tensor having a specified ``shape`` and filled with ``value``.
```

- 你的 Return 少了个 s, 我们要求按照 Google 风格指南，使用描述性风格而不是命令式风格，需要加上。
- 连续出现了两个 shape
- 需要参考参考 《 数组 API 标准 》中所定义的规格和约定提供文档字符串。


Refs:

https://megengine.org.cn/doc/stable/zh/development/docs/python-docstring-style-guide.html

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
>      dtype=None,
在这里帮助我们加上一个 `*` 来区分 `dtype` 和 `device` 这两个仅关键字参数吧～

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        dtype(:attr:`.Tensor.dtype`): output tensor data type. If ``dtype`` is ``None``, the output tensor
```suggestion
        dtype (:attr:`.Tensor.dtype`): output tensor data type. If ``dtype`` is ``None``, the output tensor
```

出于排版阅读性要求，这里统一加一个空格。

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        device(:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
```suggestion
        device (:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
```

出于排版阅读性要求，这里统一加一个空格。

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
《标准》中特别提示：

If dtype is None and the fill_value exceeds the precision of the resolved default output array data type, behavior is left unspecified and, thus, implementation-defined.

因此最好在这个 API 中对描述到的情况进行验证，也加上一个 Note.

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
>          shape: output tensor shape.
`shape` 和 `value` 可以按照 Docstring 指南的说明覆盖类型提示。

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        >>> F.full((2, 2), [1, 2])
你这里展示了一种传入的 `value` 参数为 list of ints 而不仅仅是 scalar 的用法，如果你觉得希望用户平时这样用，就应该在对应的参数的描述和类型提示中进行详细的说明；如果你不希望用户这样用，就不应该给出相应的例子。

2021-12-10 08:38 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        >>> F.full((2, 2), [1, 2])
我们的原则是优先以 《数组 API 标准》作为参考，而非 NumPy API 实现。

2022-09-28 11:00 UTC, kagome1007 commented
因长期未有后续操作，已交由其他同学处理。感谢对 MegEngine 的支持，期待后续你的贡献哦！

2022-09-28 11:00 UTC, closed without merging