docs(mge/functional): update functional.zeros docstring
MegEngine/MegEngine pull request #410
Opened 2021-12-10 07:46 UTC by TaoweiZhang

Fix: #230

- 按照[《Python 文档字符串风格指南》](https://megengine.org.cn/doc/stable/zh/development/docs/python-docstring-style-guide.html)中的说明，发现`zeros`在《数组 API 标准》中存在[标准定义](https://data-apis.org/array-api/latest/API_specification/creation_functions.html#zeros-shape-dtype-none-device-none)，因此使用了《标准》中的文档字符串作为描述内容。
- 为`shape`、`device`新增了类型提示
- 用`>>>`标准doctest风格替换了原本的`testcode`风格样例

### 翻译对比如下：
---
Summary:

- Returns a new tensor having a specified shape and filled with zeros.
- 返回一个具有指定形状的全0张量。

Args:
- shape (`int` or sequence of ints): the shape of the output tensor.
- shape (`int` or sequence of ints): 输出张量的形状.

Keyword args:
- dtype (:attr:`.Tensor.dtype`): output tensor data type. Default: ``float32``.
- dtype( :attr:`.Tensor.dtype`): 输出张量的数据类型。默认值：`float32`.

- device (:attr:`.Tensor.device`): device on which to place the created tensor. Default: ``None``.
- device( :attr:`.Tensor.device`): 用来放置所创建张量的设备。默认值：`None`.

Returns:

- a tensor containing zeros.
- 一个全0张量。

2021-12-10 07:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=410) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=410) it.</sub>

2021-12-10 07:48 UTC, TaoweiZhang commented
#230

2021-12-10 08:45 UTC, MegChai requested changes

2021-12-10 08:45 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        .. testoutput::
```suggestion
```
多了一行代码。

2021-12-10 09:19 UTC, MegChai approved these changes
Others, LGTM.

请利用 git rebase 功能将所有 commit 合并成一个，以便合入。

2021-12-10 09:43 UTC, TaoweiZhang commented
我第一次提PR，现在我应该怎么做，才能把所有commit合并成一个啊？

2021-12-10 10:47 UTC, MegChai commented
> 我第一次提PR，现在我应该怎么做，才能把所有commit合并成一个啊？ @MegChai

没关系，可以参考：https://github.com/MegEngine/MegEngine/pull/399#issuecomment-986881068

或者 GIYF(Google Is Your Friend) 网络上搜索相关关键字应该会看到很多教程，搞懂一次后面就不会懵了

2021-12-10 12:47 UTC, TaoweiZhang commented
> > 我第一次提PR，现在我应该怎么做，才能把所有commit合并成一个啊？ @MegChai
> 
> 没关系，可以参考：[#399 (comment)](https://github.com/MegEngine/MegEngine/pull/399#issuecomment-986881068)
> 
> 或者 GIYF(Google Is Your Friend) 网络上搜索相关关键字应该会看到很多教程，搞懂一次后面就不会懵了

我想这次我一个人估计解决不了这个问题了，我想为您开启协作权限，我应该怎么做呢？麻烦您了。（我给您发了邮件，但我感觉这个的效率好像更高点）

2021-12-10 15:13 UTC, TaoweiZhang commented
我看到我的commit只有一条，然后在这个PR里有一条您的commit，我不知道在git上应该进行什么操作才能把您的commit拉到我自己的log里，看了[#339(comment)](https://github.com/MegEngine/MegEngine/pull/399#issuecomment-986881068)，也搜了很多帖子来看，还是没有解决这个问题，麻烦您了。

2021-12-11 13:07 UTC, MegChai approved these changes
Others, LGTM.

十分感谢 @TaoweiZhang 花时间积极地研究了一下 `git rebase` 的正确用法，相信收获也挺大的，这会让该 PR 更快地被合入。

2021-12-13 07:17 UTC, haolongzhangm commented
LGTM

2021-12-13 08:57 UTC, MegChai approved these changes
LGTM

2021-12-13 11:48 UTC, MegChai commented
CI 挂了，原因是 one_hot 的单元测试中使用到了 zeros 这个接口，但使用不规范。这个 PR 要求使用 zeros 接口时对于 `dtype` 和 `device` 参数需要指定关键字参数（Keyword Args），因此我们需要再提交一个 commit 来修复 one_hot 单元测试中不规范的写法。之前已经有一个 PR #399 遇到了类似的问题 ，可以作为参考：

https://github.com/MegEngine/MegEngine/pull/399/commits

2021-12-13 15:00 UTC, TaoweiZhang commented
> CI 挂了，原因是 one_hot 的单元测试中使用到了 zeros 这个接口，但使用不规范。这个 PR 要求使用 zeros 接口时对于 `dtype` 和 `device` 参数需要指定关键字参数（Keyword Args），因此我们需要再提交一个 commit 来修复 one_hot 单元测试中不规范的写法。之前已经有一个 PR #399 遇到了类似的问题 ，可以作为参考：
> 
> https://github.com/MegEngine/MegEngine/pull/399/commits

已修复 one_hot 单元测试中不规范的写法。

2021-12-14 03:47 UTC, MegChai approved these changes
Others, LGTM.

2021-12-28 09:20 UTC, TaoweiZhang commented
为什么这个PR还是In Progress状态呢？

2022-01-05 04:41 UTC, tpoisonooo commented
提供一下俺发 pr 的操作：
先按[这个文档](https://github.com/MegEngine/MegFlow/blob/master/docs/how-to-contribute.zh.md)分两个 remote， origin 是我自己的remote；megvii 是官方的 remote。

```bash
切到 megvii 的  master
$ git checkout megvii/master

在 megvii master 基础上创建分支
$ git checkout -b my-awesome-branch
... 一通修改
$ git fetch megvii

rebase 一下，可能有其他人的合入
$ git rebase megvii/master

推到自己的 remote 上，有写权限
$ git pull origin my-awesome-branch
```

2022-01-05 05:26 UTC, TaoweiZhang commented
> 

感谢！！！

2022-01-05 05:43 UTC, MegChai approved these changes
LGTM

2022-01-05 06:35 UTC, merged