docs(mge/functional): update functional.ones_like docstring
MegEngine/MegEngine pull request #421
Opened 2021-12-26 12:40 UTC by Asthestarsfalll

fix #233

2021-12-27 08:07 UTC, MegChai requested changes

2021-12-27 08:07 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
> +        >>> input = F.arange(1, 7, dtype='int32').reshape(2,3)
感觉这个 arange(1, 7) 有点强迫症，毕竟例子中也没有输出 input 来看里面的值，直接用 arange(6) 就好了，你觉得呢？这个 ones_like API 更在意的是形状 shape.

2021-12-27 08:07 UTC, MegChai commented on imperative/python/megengine/functional/tensor.py
>          inp: input tensor.
这里没有添加类型提示

2021-12-27 11:11 UTC, Asthestarsfalll commented
修改了下，不过不太清楚`SymbolVar`是什么

2021-12-27 16:25 UTC, MegChai approved these changes
需要 rebase 一下，LGTM

2021-12-28 04:11 UTC, XindaH commented
麻烦合并为一个 commit

2021-12-28 06:52 UTC, Asthestarsfalll commented
已合并

2021-12-29 07:27 UTC, GetUpEarlier commented
LGTM

2021-12-29 07:30 UTC, GetUpEarlier approved these changes
LGTM

2022-01-14 08:10 UTC, merged