feat(opr): add bias_kv, zero_attn, reslink support for naive proxy ba…
MegEngine/MegEngine pull request #517
Opened 2023-09-28 07:14 UTC by BigWhitePolarBear

…ckend

OSPP 2023: https://summer-ospp.ac.cn/org/prodetail/23a210224?lang=zh&list=pro

后面再补充测试内容。

2023-09-28 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=517) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegEngine?pullRequest=517) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegEngine?pullRequest=517) it.</sub>

2023-10-09 04:38 UTC, Ysllllll commented
补个python test吧

2023-10-09 10:55 UTC, Ysllllll requested changes

2023-10-09 11:25 UTC, BigWhitePolarBear commented on src/opr/include/megbrain/opr/rand.h
> +
这些问题我都注意到了的T T，最后会一次性更新。

2023-10-09 11:26 UTC, BigWhitePolarBear commented on imperative/tablegen/generated/opdef.cpy.inl
> +        } CATCH_ALL(-1)
是的

2023-10-29 05:08 UTC, Ysllllll approved these changes

2023-11-15 04:08 UTC, closed without merging